### ISSUE TITLE
Demo for Redaction Tool

### ISSUE THREAD

**Issue by lovedota** [Accusoft/hello-prizmdoc-viewer-with-nodejs-and-html#1]
Hi guys
We from Ansarada Company currently have a trial with Accusoft, we try to find an example code for Redaction Tool which is working in https://www.accusoft.com/demos/demo-redaction/
Please provide this demo in this repository so that we can play around.

**Comment by adamjcooper** [comment]
Hey @lovedota, thanks for contacting us.

Yeah, the [redaction demo on our website](https://www.accusoft.com/demos/demo-redaction/) is something totally separate from [this introductory node.js sample](https://github.com/Accusoft/hello-prizmdoc-viewer-with-nodejs-and-html) and, at the moment, the source code for that demo is not available on GitHub. However, our Sales Engineering team would be happy to speak with you to understand what it is you're trying to accomplish and provide guidance and sample code to get you started. If you're not already working with a Sales Engineer, the best thing to do would be to email info@accusoft.com.

Since this issue you opened is not a problem with this introductory sample itself, I intend to close it. But thanks for your question!
